### PR TITLE
Fixes C4706

### LINKED ISSUE #201: Fix Warning C4706 - Using result of assignment as condition
A recent change has created a lot of compiler warnings:
```cpp
src/Configuration.cpp:219:18: warning: using the result of an assignment as a
      condition without parentheses [-Wparentheses]
                while (xmlNode = root->iterateChildren(xmlNode)) // warn...
                       ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This is the result of many lines similar to the following:
```cpp
		while (xmlNode = root->iterateChildren(xmlNode)) // warning C4706: intended
```

Previously, these lines had an extra set of parenthesis which were silencing the warning:
```cpp
		while ((xmlNode = root->iterateChildren(xmlNode)))
```

----

It may be possible to provide a bit of support code to enable [range-based for loops](https://en.cppreference.com/w/cpp/language/range-for) to replace those `while` loops. In particular, the existence of `begin` and `end` methods can allow the compiler to generate a range-based for loop.

There are two ways to use `begin`/`end`. Either as member methods on a class, or as free floating methods which take an iterable parameter. If we wish to avoid modifying existing classes (perhaps from within the XML library), we can instead use the later form of free floating methods.

### PR DESCRIPTION
**Pull request by cugone**
Closes #201

Fixes the C4706 warnings

### CODE REVIEW

**Comment by DanRStevens** [comment]
Tagging PR #232 as related. I think that PR may have actually eliminated the warnings in Issue #201. It wasn't exactly the most satisfactory fix though.

**Comment by cugone** [comment]
Weird. I was still getting them in my debug build (hence this PR).

**Comment by DanRStevens** [comment]
There may be some confusion over two different error messages here. In Issue #201, the error quoted is a Clang error message. The C4706 in the comment is an MSVC reported error message.

I haven't been seeing the MSVC error message on AppVeyor, though that may be a difference in analysis settings for the `Debug` configuration.

I think what happened is the two compilers were fighting about what was worse. MSVC complained about something, so code was changed to fix the warning. Then Clang started complaining about the fixed code. Or maybe the other way around. I can't remember now.

Regardless, neither compiler seems to be complaining now, so that's good.

**Comment by DanRStevens** [comment]
After re-reading issue #201 I noticed the solution here is very similar to a related solution that Leeor suggested for a different block of code. As the tests are passing, I'm going to go ahead and merge this.

**Pull request merged**
