### PR TITLE
Convert copyright symbols to Unicode

### PR DESCRIPTION
**Pull request by DanRStevens**
Related: #922

I noticed my editor wanted to auto correct the copyright symbols to a Unicode encoding. It makes it frustrating to edit files that aren't already converted, as the change either adds noise to commits, or needs to be manually skipped when adding changes.

Would be nice to get confirmation from people using Windows that Unicode copyright symbols display correctly in Visual Studio.

### CODE REVIEW

**Comment by cugone** [comment]
Confirmed, they display correctly even if the project tells the compiler to Use Multi-byte Characterset.

**Comment by DanRStevens** [comment]
Thank you.

**Comment by cugone** [comment]
I did notice that even though it displays correctly in visual studio, GitKraken does not and they show up as the questionmark glyph. It's probably a setting that I need to change somewhere.

**Comment by DanRStevens** [comment]
Do you mean the old encoding, or the new encoding?

https://superuser.com/questions/1405232/how-to-configure-gitkraken-to-iso-8859-1-encoding
> For the time being Gitkraken supports only UTF-8

**Comment by cugone** [comment]
The new encoding shows up as the question mark in GitKraken file views. I found that question as well. The poster specifically said the problem appears as stashing/popping changes the encoding and another question on SO used hunk staging and they said that's that what caused it. I do not use hunk staging and instead use line-by-line, selected lines, or whole-file staging and simple tests did not reproduce the issue and the glyph correctly rendered in visual studio and did not change the glyph between saves, stages in and out, stashing/popping, and push/pulls; so, I wouldn't worry about it until it actually happens.

**Pull request merged**
