### PR TITLE
Tier-0 File logger class

### LINKED ISSUE #393: FileLogger might be helpful
I was looking at OPHD and noticed it used an odd hack to log to a file. A proper multi-threaded FileLogger class might be helpful to include in the engine.

### PR DESCRIPTION
**Pull request by cugone**
Closes #393

Related #394

This is an initial implementation of a multi-threaded file logging class. The bare bones log and logline functions. More can be added later like tags and time stamps.

Also included are classes and functions that support the multi-threadedness of this class and can be used in the future to support a Job System.

### CODE REVIEW

**Comment by cugone** [comment]
Can you enumerate those concerns so I can get a better feel for why you have them? What is your definition of complex? It seems to me the code implemented here is pretty straightforward. The gross Unicode stuff is only there because Windows requires its thread names to be in `L""` "Unicode" format. Everything else is literally single-line functions.

As for overkill, no. This is a *dead simple* logger. 

Here's an example of why any logging system should be threaded and an example of a more complex one: https://github.com/tocchan/guildhall/tree/master/sd3/assignments/a03

Throwing 1000+ log messages at it *per frame* and your game doesn't even notice.

You keep thinking in terms of the one game being written right now "because it's turn based, we don't have to worry about it." What if someone wanted to take the engine and make a different game?

Additionally, I can see a situation where each entity (tile, structure, population system, mining, resource manager, etc) in the game is logging many times per frame at least at the beginning of the turn or end for debugging or just general information. With enough active tiles, if the system isn't threaded it will stall your simulation every turn and will make your users complain that the game runs really slow or the time between turns takes "forever" or the UI is unresponsive after a certain number of buildings or colony size.

**Comment by ldicker83** [comment]
I'm not opposed to a multi-threaded logger, I'm just wondering if it's really within the scope of NAS2D? At least for now? I don't want to discourage innovation but I also am unsure about reinventing wheels when other logging libraries are already available and easily included in projects where it's needed?

Most of the logging done by NAS2D itself is really only in debug builds (where performance concerns are effectively non-existent) or in cases of exceptions being thrown so the effect is almost unnoticeable. I can see this being an issue for games that are real-time that use a lot of logging but in those cases I would encourage the end user to roll their own or use an established library.

**Comment by DanRStevens** [comment]
I think this is out of scope.

Current logging produces about a page of text. It's not much. There is little reason to optimize it with threads. I would really like to avoid long term maintenance costs of threaded logging code in this library.

The current logging output often seems like an artifact of the old error handling code. Much of it should be converted to exceptions and/or unit tests. In particular, developers who use the library may want full control over what is output to the user, so we should avoid direct calls to `std::cout` and `std::cerr` from within the library. Instead, an exception based approach should be used, so developers can catch exceptions and relevant messages in their own code and decide what to do with it. That might mean printing it to the console, logging it to a file, or outputting it in some sort of graphical console, or even just in a message box (for early development).

My preference is to reduce and remove logging from this library, and make it an external concern.

Along those lines, if the logging code suggested here is generic, perhaps it can become its own library.

**Comment by DanRStevens** [comment]
As per my comment in the associated issue, I think I'm going to close this as not an area of priority for us right now.

I'll leave the branch for a few days in case you want to do anything with the code.

**Pull request closed without merging**
