### PR TITLE
Upgrade to Visual Studio 2019

### PR DESCRIPTION
**Pull request by ldicker83**
This PR creates Visual Studio 2019 solution files and upgrades the appveyor build environment to use VS2019.

### CODE REVIEW

**Comment by ldicker83** [comment]
Forgot to mention in commit notes, this VS project settings ref's #136. I see a distinct change in build times on my local machine. All builds are currently queued on appveyor so waiting for it to do its thing.

**Comment by DanRStevens** [comment]
I was just going to say, oh sweet, AppVeyor already supports VS2019, then saw your last commit about it being the Preview version. Still, should be good enough.

----

Seems there is a problem with the SDL2 redist NuGet Package:
```
C:\projects\nas2d-core\proj\vs2017\NAS2D.vcxproj(322,5): error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is packages\sdl2.nuget.redist.2.0.9\build\native\sdl2.nuget.redist.targets.
```

This is odd, because the package seems to have been installed:
```
nuget restore proj/vs2019
MSBuild auto-detection: using msbuild version '16.0.360.33175' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\bin'.
Restoring NuGet package sdl2.nuget.redist.2.0.9.
Restoring NuGet package sdl2.nuget.2.0.9.
  GET https://api.nuget.org/v3-flatcontainer/sdl2.nuget.redist/2.0.9/sdl2.nuget.redist.2.0.9.nupkg
  GET https://api.nuget.org/v3-flatcontainer/sdl2.nuget/2.0.9/sdl2.nuget.2.0.9.nupkg
  OK https://api.nuget.org/v3-flatcontainer/sdl2.nuget/2.0.9/sdl2.nuget.2.0.9.nupkg 18ms
Installing sdl2.nuget 2.0.9.
  OK https://api.nuget.org/v3-flatcontainer/sdl2.nuget.redist/2.0.9/sdl2.nuget.redist.2.0.9.nupkg 55ms
Installing sdl2.nuget.redist 2.0.9.
Adding package 'sdl2.nuget.redist.2.0.9' to folder 'C:\projects\nas2d-core\proj\vs2019\packages'
Added package 'sdl2.nuget.redist.2.0.9' to folder 'C:\projects\nas2d-core\proj\vs2019\packages'
```

I noticed in the original error message, it mentions `build\native\sdl2.nuget.redist.targets`, so perhaps the package is missing some native component.

----

To automatically close an issue when the PR is merged, the top post needs to reference the issue with `close`/`fix`/`resolve` (or conjugated forms of those). Any subsequent post will only create a reference to the Issue, not auto close it on merge:
https://help.github.com/en/articles/closing-issues-using-keywords
I'd recommend editing the first post to create a close reference for the Issue.

**Comment by ldicker83** [comment]
Great, suddenly TravisCI is failing again on Linux builds due to ancient SDL2 versions (using 2.0.5 instead of 2.0.9). It may be time to disable or remove TravisCI permanently.

**Comment by ldicker83** [comment]
For now I've turned off TravisCS. Merged changes from several of the PR's that Daniel pushed. Going to wait for these tests to complete and if they look good I'll move forward with this commit.

I will leave the VS2017 project in place for now, perhaps @cugone can get the nuget packages working again with the VS2019 project -- vcpkg is a lot easier and the libraries are much more up to date but it takes a lot longer for the builds to complete (has to build each library instead of downloading prebuilt binaries).

**Comment by cugone** [comment]
I was under the impression there was a desire to keep using VS2017 for now and wait for appveyor to upgrade to a non-preview builds of 2019.

**Comment by cugone** [comment]
Is there a way to only install the vcpkgs for the appropriate version being built? Right now both builds, x86 and x64, are installing both x86 and x64 vcpkgs. Only installing the x86 version for the x86 build and vice versa will considerably cut down on build time.

**Comment by ldicker83** [comment]
> Is there a way to only install the vcpkgs for the appropriate version being built? Right now both builds, x86 and x64, are installing both x86 and x64 vcpkgs. Only installing the x86 version for the x86 build and vice versa will considerably cut down on build time.

It would, but it seems to be a moot point since you got it working properly via nuget. Will merge that version and close/delete this branch.

Thanks!

**Comment by DanRStevens** [comment]
> I was under the impression there was a desire to keep using VS2017 for now and wait for appveyor to upgrade to a non-preview builds of 2019.

Admittedly I feel a little foolish on this one. I didn't realize AppVeyor already had a VS 2019 preview version. I only saw the VS 2017 version option. Additionally I had just recently spent 2 days downloading and setting up a VS 2017 environment, and wasn't eager to go through that again so soon. Though Leeor did kind of sell me on it by saying the upgraded files should still work with VS 2017.

So yeah, maybe I still had a bit of a desire to stick with VS 2017, but ehh. Maybe I'm being a stick in the mud. Leeor is the one developing from Windows, and it is his project.
`¯\_(ツ)_/¯`

**Pull request closed without merging**
