### PR TITLE
Use parameter packs for delegates

### PR DESCRIPTION
**Pull request by DanRStevens**
I got to looking at this code after doing the `musicComplete` callback change. It reminded me of the idea to reduce the bulk of the code by using template parameter packs. I thought I'd try my hand at it, now that I'm a little more familiar with templates. It seemed to go well.

~~I think we should probably write test code first, before merging it. Meanwhile, I thought I'd share this now and see what people think.~~ Edit: Unit tests added by PR #326.

----

~~Edit: I haven't yet touched the related `Signal` class.~~ Edit: Done.

### CODE REVIEW

**Comment by DanRStevens** [comment]
Rebased on master after merging #326. This ensures the new unit tests will be run for these code changes.

**Comment by cugone** [comment]
You forgot to add the new test cpp files to the Visual Studio project. None of the new tests are being run by AppVeyor.

**Comment by DanRStevens** [comment]
Oh geeze, thanks. This is why we have reviews.

**Comment by cugone** [comment]
It's my fault too. I didn't pull down the PR locally, just reviewed it via the web interface.

**Pull request merged**
