### PR TITLE
Move CONVENTIONS.md to more-visible wiki page

### PR DESCRIPTION
**Pull request by cugone**
Copied the contents of `CONVENTIONS.md` as a page on the wiki instead of an easily missed `.md` file in the source.

### CODE REVIEW

**Comment by DanRStevens** [comment]
Huh, there's a wiki?

I'm not seeing where this stuff has moved to.

**Comment by cugone** [comment]
Click on the "Wiki" tab at the top: https://github.com/lairworks/nas2d-core/wiki
The list of pages is on the right. Added page: https://github.com/lairworks/nas2d-core/wiki/Style-Guide-and-Code-Conventions

**Comment by DanRStevens** [comment]
I've completely ignored the wiki this whole time.

----

One point of caution, things in the repository are automatically cloned and transferred naturally by Git. This provides natural backup, and an easy path to transition to a new hosting provider. Things on the wiki are not automatically backed up or transferred. If we ever move hosting providers, we lose the external items such as wikis, issues, and project boards, or are possibly forced to port them over manually.

**Comment by cugone** [comment]
> I've completely ignored the wiki this whole time.
> 
> One point of caution, things in the repository are automatically cloned and transferred naturally by Git. This provides natural backup, and an easy path to transition to a new hosting provider. Things on the wiki are not automatically backed up or transferred. If we ever move hosting providers, we lose the external items such as wikis, issues, and project boards, or are possibly forced to port them over manually.

Wikis are just repositories. They can be cloned just like any other by appending `.wiki.git` to the path:
https://github.com/lairworks/nas2d-core.wiki.git

Just tested it and I was able to clone the wiki locally.

Ref: https://gist.github.com/subfuzion/0d3f19c4f780a7d75ba2

**Pull request closed without merging**
